# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-Remove
version:      0.31
version_from: lib/File/Remove.pm
installdirs:  site
requires:
    File::Glob:                    0
    File::Spec:                    0.84

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
