--- #YAML:1.0
name:                File-Remove
version:             1.40
abstract:            Remove files and directories
license:             ~
author:              
    - Richard Soderberg <rs@localdomain>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    File::Copy:                    0
    File::Glob:                    0
    File::Path:                    0
    File::Spec:                    0.84
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
