---
abstract: 'Remove files and directories'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  Test::More: 0.42
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
module_name: File::Remove
name: File-Remove
no_index:
  directory:
    - inc
    - t
requires:
  File::Copy: 0
  File::Glob: 0
  File::Path: 0
  File::Spec: 0.84
  perl: 5.005
version: 1.41
