--- #YAML:1.0
name:                File-Remove
version:             0.36
abstract:            Remove files and directories
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    File::Copy:                    0
    File::Glob:                    0
    File::Path:                    0
    File::Spec:                    0.84
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Richard Soderberg <rs@localdomain>
